all:

pass:
	gcc pass_filefind.c filefind.o -o pass

fail:
	gcc fail_filefind.c filefind.o -o fail

test:
	gcc test_filefind.c filefind.o -o test

# run:


clean:
	rm -rf pass
	rm -rf fail
	rm -rf test